### ISSUE TITLE
Makefile:8: recipe for target 'noun_closure.tsv' failed

### ISSUE THREAD

**Issue by PkuRainBow** [facebookresearch/poincare-embeddings#1]
Please help me~

Do I miss something? It seems that some files in your Makefile is missing?

```
mammal_closure.tsv: noun_closure.tsv
	cat noun_closure.tsv | grep -e "\smammal.n.01" | cut -f1 | sed 's/\(.*\)/\^\1/g' > mammals.txt
	cat noun_closure.tsv | grep -f "mammals.txt" | grep -v -f mammals_filter.txt > mammal_closure.tsv

noun_closure.tsv:
$(PYTHON) transitive_closure.py
```
And I got this error log~ 

![default](https://user-images.githubusercontent.com/4639578/35428085-26dea584-02a8-11e8-99be-5f0b2a020baa.png)

**Comment by MeteKem** [comment]
The NLTK installation in your Python environment does not include wordnet by default. You need to install it by launching the Python interpreter and following the instructions:
```
>>> import nltk
>>> nltk.download('wordnet')
```

**Comment by gballardin** [comment]
Downloading `wordnet` with nltk, like suggested above, solved this problem for me.

**Comment by danielhavir** [comment]
Same for me, downloading nltk and switching from python 3.5 to python 3.6 fixed this for me (I guess it's the f string in the `transitive_closure.py` that cause this error for me).

**Comment by mnick** [comment]
As @MeteKem mentioned, it is sufficient to download the wordnet corpus via the standard NLTK mechanism,
