### ISSUE TITLE
Unexplained DataLoader output

### ISSUE THREAD

**Issue by dpappas** [facebookresearch/poincare-embeddings#14]
I tried running the example provided.
In the file "train.py" and specifically in the function train each instance of the data matrix has a shape of (1,52).
This is good since each instance has 
in the first index the node we focus on,
in the second index a true neighboring node,
and the next 50 are random nodes.

On the other hand in this line :
 `for inputs, targets in loader:`
we get batches of size (batch_size,7) and i understand that each item in these vectors corresponds to an index in the embedding matrix (and a node as well). 

If these 7 numbers are the nodes why don't we get 52 as in the data matrix ? 
If these numbers are not the candidate neighbors then could you explain what are they ? 

Thank you in advance!

**Comment by almightyGOSU** [comment]
In model.py > SNGraphDataset > __getitem__(self, i): [model.py Line 177](https://github.com/facebookresearch/poincare-embeddings/blob/9aecb8634abbbc23338c2b5e5bb61ca517581bef/model.py#L177)

The number of negative samples used during the **burn-in period** is **10%** of the default setting (i.e. 50).
Hence, during the burn-in period, there will only be 5 negative samples.
That's how you end up with the 7 nodes (_only during the burn-in period_).
