### ISSUE TITLE
Unable to use my own data

### ISSUE THREAD

**Issue by NooneBug** [facebookresearch/poincare-embeddings#17]
I'm trying to use my own data in tsv format but I have a problem:

The console returns me this message: 

"./poincare-embeddings/model.py", line 156, in __init__ assert len(objects) == nents, 'Number of objects do no match'
AssertionError: Number of objects do no match

I'd like to know what is the meaning of this assertion . Even because if I put a comment on the line, everything works.

Thanks

**Comment by carricky** [comment]
same problem here

**Comment by lematt1991** [comment]
This should be resolved now.  Please re-open a new task if you have issues with using your own data again.

**Comment by Clarioooo** [comment]
Which file is model.py? Has it been renamed embed.py? I want to use the code on another dataset, but I just changed the file 'mammals_filter.txt' opened in transitive_closure.py, but it seems that the generated data is still mammals. Am I running it wrong?
<img width="732" alt="image" src="https://github.com/facebookresearch/poincare-embeddings/assets/83835647/f546514b-850c-49c7-ac88-2b57d7dc9659">
