### ISSUE TITLE
KeyError: 'Traceback

### ISSUE THREAD

**Issue by loveJasmine** [facebookresearch/poincare-embeddings#18]
mldl@ub1604:~/ub16_prj/poincare-embeddings$ NTHREADS=2 ./train-nouns.sh 
Using 2 threads
slurp: objects=82115, edges=743086
Indexing data
json_conf: {"distfn": "poincare", "dim": 10, "lr": 1, "batchsize": 50, "negs": 50}
Burnin: lr=0.01
'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/mldl/ub16_prj/poincare-embeddings/model.py", line 185, in __getitem__\n    if n not in self._weights[t]:\nKeyError: tensor(23511)\n'
Traceback (most recent call last):
  File "/home/mldl/ub16_prj/poincare-embeddings/train.py", line 19, in train_mp
    train(model, data, optimizer, opt, log, rank, queue)
  File "/home/mldl/ub16_prj/poincare-embeddings/train.py", line 46, in train
    for inputs, targets in loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/mldl/ub16_prj/poincare-embeddings/model.py", line 185, in __getitem__\n    if n not in self._weights[t]:\nKeyError: tensor(23511)\n'
'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/mldl/ub16_prj/poincare-embeddings/model.py", line 185, in __getitem__\n    if n not in self._weights[t]:\nKeyError: tensor(23511)\n'
Traceback (most recent call last):
  File "/home/mldl/ub16_prj/poincare-embeddings/train.py", line 19, in train_mp
    train(model, data, optimizer, opt, log, rank, queue)
  File "/home/mldl/ub16_prj/poincare-embeddings/train.py", line 46, in train
    for inputs, targets in loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/mldl/ub16_prj/poincare-embeddings/model.py", line 185, in __getitem__\n    if n not in self._weights[t]:\nKeyError: tensor(23511)\n'

**Comment by EskreisWinkler** [comment]
I got this exact same error! I would very much like to find out how to resolve it!! I am not so clear how the DataLoader function is working, it seems like it is not receiving an object of the type that it wants. My error was the following:


Traceback (most recent call last):
  File "embed.py", line 174, in <module>
    train.train(model, data, optimizer, opt, log, 0)
  File "/home/localpackages/poincare-embeddings-master/train.py", line 46, in train
    for inputs, targets in loader:
  File "/home/anaconda/envs/mmf_anaconda2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda/envs/mmf_anaconda2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/anaconda/envs/mmf_anaconda2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/Users/jonathaneskreis-winkler/localpackages/poincare-embeddings-master/model.py", line 185, in __getitem__\n    if n not in self._weights[t]:\nKeyError: tensor(289)\n'

**Comment by lematt1991** [comment]
The current implementation is written for PyTorch 0.3.0.  We are working on an update for the new version of PyTorch, but haven't had time to push it out yet.  In the meantime, just use PyTorch 0.3.0 (`conda install pytorch=0.3.0 -c pytorch`)

**Comment by EskreisWinkler** [comment]
This does not appear to have an impact on the error I am seeing. I did what you said and I just reran the code but got the same error.

**Comment by hhajri** [comment]
I got the same error about dataloader.py

**Comment by sufengniu** [comment]
Hello, @carricky, I also encountered this issue, and just as you mentioned, they use tensor as keys of a dict. I did some tries to fix it, but not success as well. I just wonder how did you overcome this issue? Thanks in advance!

**Comment by carricky** [comment]
Hi @sufengniu, you can follow the pull request here to fix this. https://github.com/facebookresearch/poincare-embeddings/pull/13

**Comment by lematt1991** [comment]
This should now be resolved.
