### ISSUE TITLE
Minor typo (distfn) in embed.py

### ISSUE THREAD

**Issue by ylhsieh** [facebookresearch/poincare-embeddings#2]
The line https://github.com/facebookresearch/poincare-embeddings/blob/35c232207bc62f13c35fee844ccb6932aae70709/embed.py#L136 
should be
`elif opt.distfn == 'euclidean': `

**Comment by mnick** [comment]
Thanks for reporting. Fixed in eea79e0101a9eb2950aaaf205a97de21ab9066f6
