### ISSUE TITLE
Poincare Embedding for Images

### ISSUE THREAD

**Issue by kris-singh** [facebookresearch/poincare-embeddings#21]
I read the paper but I could not understand why Poincare embedding cannot be used for images embedding learning. Images can also have a hierarchical structure eg in the case of fashion images etc. I know this is off topic but I would be really grateful if somebody can help me.

**Comment by 0xSameer** [comment]
@kris-singh  
I haven't read the paper but maybe check it out:
[Khrulkov et al. --- Hyperbolic Image Embeddings](https://arxiv.org/abs/1904.02239)
