### ISSUE TITLE
Embedding of Tree Structures: root no in the center of the disk

### ISSUE THREAD

**Issue by federicodassereto** [facebookresearch/poincare-embeddings#26]
Hi,
I'm dealing with embedding of hierarchical structures (a tree) and I used your algorithm. 
It works, but when I visualise the 2D or 3D embedding the root of the tree is not in the center of the disk.
Is there some command or flag to add to the code? Or is the root supposed to be in the center on his own?

**Comment by lematt1991** [comment]
Is the root the lowest norm embedding (closest to the center)?  There isn't anything enforcing it to be at the center, but should have the lowest norm.  Also, how are you getting your 2/3 dimensional embeddings?  Normal dimensionality reduction techniques aren't sufficient.  For our 2d plot, we train in two dimensions.

**Comment by federicodassereto** [comment]
I produced the embeddings in 2 and 3 dimensions respectively. The element with the lowest norm is not the root, despite the structure I'm considering is definitely a tree.

**Comment by lematt1991** [comment]
Then it's likely you aren't using the optimal hyper parameters.  You can tune these using the output from "mean_rank" and "map_rank"

**Comment by federicodassereto** [comment]
Ok, thanks a lot for your help!
