### ISSUE TITLE
How to get vector for a node?

### ISSUE THREAD

**Issue by BehroozMansouri91** [facebookresearch/poincare-embeddings#27]
After training the model, how can we get the vector for the concepts we have embedded?
Like the Gensim word2vec library where we could easily call a function like model.getvector("Man").

**Comment by lematt1991** [comment]
The checkpoint that gets saved will have both the embedding table and the list of objects in the same order.  Assuming you have an embedding for the word "Man", you can do the following:

```Python
import torch, numpy as np
chkpnt = torch.load('<path to checkpoint>')
embeddings = chkpnt['embeddings']
objects = np.array(chkpnt['objects'])
idx = np.where(objects == 'Man')[0]
v = embeddings[idx]
```
