### ISSUE TITLE
Pretrained embeddings

### ISSUE THREAD

**Issue by lambdaofgod** [facebookresearch/poincare-embeddings#30]
Did you share results of your embeddings?
If yes, for what model did you share?
If not, can you at least share information on running time for your results?

**Comment by lematt1991** [comment]
We have not shared pretrained embeddings, but have included scripts to reproduce results.  `train-mammals.sh` and `train-nouns.sh`.  Training time for mammals should only be a few minutes.  Training time for nouns is quite a bit longer ~1 day.

**Comment by lematt1991** [comment]
Closing for now.  Please re-open a new issue if you have further questions.
