### ISSUE TITLE
How can I get result for each epoch?

### ISSUE THREAD

**Issue by huajianjiu** [facebookresearch/poincare-embeddings#33]
Hi.

I know little about multiprocessing.
I wonder why there is only one output checkpoint while the 205th line in embed.py save the result for each epoch.

I want to visualize how the embedding changes during training.
How can I get the embeddings after each epoch?

Thank you.

**Comment by lematt1991** [comment]
You can comment out [this](https://github.com/facebookresearch/poincare-embeddings/blob/master/embed.py#L217) line to keep all checkpoints.

**Comment by huajianjiu** [comment]
> You can comment out [this](https://github.com/facebookresearch/poincare-embeddings/blob/master/embed.py#L217) line to keep all checkpoints.

Thank you. It works!
