### ISSUE TITLE
rgrad return

### ISSUE THREAD

**Issue by HHalva** [facebookresearch/poincare-embeddings#37]
Why does rgrad return d_p rather than u; what am I missing?

    def rgrad(self, p, d_p):
        """Riemannian gradient for hyperboloid"""
        if d_p.is_sparse:
            u = d_p._values()
            x = p.index_select(0, d_p._indices().squeeze())
        else:
            u = d_p
            x = p
        u.narrow(-1, 0, 1).mul_(-1)
        u.addcmul_(self.ldot(x, u, keepdim=True).expand_as(x), x)
        return d_p

**Comment by lematt1991** [comment]
`u = d_p` and all operations on `u` are done in place (an underscore at the end of a function in pytorch indicates it operates in place.  So it doesn't matter, returning `u` would be the same

**Comment by HHalva** [comment]
(in case someone else finds it useful:  the operations with _ e.g. addcmul_ indicate in-place operations, which I didn't realize)

**Comment by lematt1991** [comment]
I'm going to close this issue.  Please open another if you have further questions.
