### ISSUE TITLE
Problem of Poincare Distance and Norm

### ISSUE THREAD

**Issue by ShaoTengLiu** [facebookresearch/poincare-embeddings#41]
Hi, I trained a 100 dimension model with *train-nouns.sh* in poincare manifold. I tested the model by calculating the **tensor.norm** of some nodes and **poincare.distance** between some nodes.

However, for **Gauss**, **Brain**, **Blue** and many other nodes near to the edge, the **norm** of them become **1.0000**, which means infinity in poincare ball. In addition, if I calculate the poincare distance between these nodes near to the edge and other nodes, the distance will be always **12.2061**, which is a little confusing.

Thanks for your attention!

**Comment by ShaoTengLiu** [comment]
For example, 
* poincare_embedding('brain.n.01').norm() = 1.0000
* poincare_distance(brain, blue) = 12.2061
* poincare_distance(brain, scientist) = 12.2061

**Comment by lematt1991** [comment]
To prevent precision issues, we clip the norm to be some number very close to 1 (usually `1 - 1e^-5`).  I believe the norm is showing `1.0000` due to rounding.  You can confirm this by doing `torch.set_printoptions(precision=10)` and then printout out the norm again.

**Comment by ShaoTengLiu** [comment]
Thanks a lot!
