### ISSUE TITLE
How to choose the best model

### ISSUE THREAD

**Issue by ShaoTengLiu** [facebookresearch/poincare-embeddings#42]
Hi. When I finished running train-nouns.sh, nouns.bin.99 ~ nouns.bin.1499 were generated. I am wondering if nouns.bin.1499 is the best model? If not, how can we decide which is the best?

**Comment by lematt1991** [comment]
You can use the `reconstruction.py` script to determine which model is best.  A higher mean_rank and lower map_rank implies a better model
