### ISSUE TITLE
Reconstruction.py gives completely different results from running evaluation

### ISSUE THREAD

**Issue by joecomerisnotavailable** [facebookresearch/poincare-embeddings#47]
Hello,

I've trained the model using train-nouns.sh, up to 1500 epochs. At the final print-out evaluation during training, performance was as expected: MAP at around .9 and mean rank around 4. However, when evaluating the model using reconstruction.py, on any checkpoint (I removed the recommended line in train.py to save all checkpoints), including the final checkpoint, I get very, very bad results. For example, the results from the final checkpoint are: `Mean rank: 44117.63953297465, mAP rank: 0.00015312198997491055`.

I investigated the code from train.py and reconstruction.py to see if I could spot what is causing the discrepancy, but I can't see it.

If I run embed.py using the final checkpoint, the first running evaluation matches the final printout from the previous run, so I at least know that the checkpoint file didn't somehow fail to contain the embeddings from the correct epoch or something. But I don't know why reconstruction.py gets different results on the same checkpoint.

Is this behavior expected?

**Comment by lematt1991** [comment]
Sorry about that!  There is an issue that we don't use consistent IDs between `reconstruction.py` and `embed.py`.  #48 should fix this.

**Comment by joecomerisnotavailable** [comment]
Ah, yes, that makes sense. Thank you for the very quick reply.
