### ISSUE TITLE
Using Adjacency Matrix Data Set

### ISSUE THREAD

**Issue by rsonthal** [facebookresearch/poincare-embeddings#49]
I would like to use the code for my own datasets. However, my data sets are graph networks and I am not sure how to the format the hdf5 file to work with your code. 

I imagine 'ids' is an array of the node 'ids' and 'weights' is a matrix for the edge weights. 

Is 'neighbors' the adjacency matrix? I don't know what 'offsets' and 'objects' should be. 

Thank you for help.

**Comment by lematt1991** [comment]
You shouldn't need to use the HDF5 format.  You can just create a CSV file columns `id1,id2,weight`.  You can follow the format of the files created by `wordnet/transitive_closure.py`

**Comment by rsonthal** [comment]
Thanks!
