### ISSUE TITLE
Evaluation benchmark and WordNet Reconstruction code

### ISSUE THREAD

**Issue by rtatgit** [facebookresearch/poincare-embeddings#53]
Hello,
"A Poincaré embedding with d = 5 achieves mean rank 1.26 and MAP 0.927 on this." After how many epochs do you arrive at these evaluation metrics? Also there is no information on how to run reconstruction.py in the readme.

**Comment by lematt1991** [comment]
As mentioned in the [README](https://github.com/facebookresearch/poincare-embeddings#example-embedding-wordnet-mammals), you can just run the `train-mammals.sh` script and it will reproduce the result.
