### ISSUE TITLE
Sample Code for Link Prediction?

### ISSUE THREAD

**Issue by AdarshMJ** [facebookresearch/poincare-embeddings#54]
Hi!
Excellent work, I was wondering if there are plans to share a sample code for setting up link prediction experiments? Also for visualising the embeddings.

Thanks!

**Comment by lematt1991** [comment]
Yes, we will release the visualization code, the link prediction reproduction code will take some more time, but we will release it.  I'm going to close this issue in favor of #45 and #10

**Comment by joshmyersdean** [comment]
Hi @lematt1991,

Was this code ever released?
