### ISSUE TITLE
How to work on datasets like wordnet verbs and mesh?

### ISSUE THREAD

**Issue by AdarshMJ** [facebookresearch/poincare-embeddings#55]
I was looking for ways to run the code on different datasets. The transitive.py code downloads the wordnet dataset, how do I specify it should download the verbs dataset as well?

Thanks in advance!

**Comment by lematt1991** [comment]
We don't currently include code that extracts the verbs transitive closure, but that should be easy enough to add.  I'll try and push it soon.

**Comment by AdarshMJ** [comment]
Thank you!
