### ISSUE TITLE
Cannot import hypernimysuite

### ISSUE THREAD

**Issue by NooneBug** [facebookresearch/poincare-embeddings#58]
Hi, 

I cloned the repository and try to replicate the experiment but the embed.py returns me an error that say that` cannot import hypernymysuite`

I checked your other repositories and I found: https://github.com/facebookresearch/hypernymysuite, I cloned and copied the folder `hypernymysuite` into `poincare-embeddings` folder and I solved the problem (I think)

This issue is opened only to know if I solved correctly the problem.

Thanks

**Comment by lematt1991** [comment]
Yes, sorry you will also need to do 

```
pip install git+https://github.com/facebookresearch/hypernymysuite.git
```
 
I'll update the `environment.yml` file shortly to reflect this updated dependency.  Sorry for the confusion!
