### ISSUE TITLE
Direct in readme the required packages

### ISSUE THREAD

**Issue by jeskreiswinkler-etsy** [facebookresearch/poincare-embeddings#60]
Install would be easier if the required packages were included in the installation - nltk, tqdm, Cython, torch. Just a suggestion!

**Comment by lematt1991** [comment]
Assuming you follow the [installation instructions](https://github.com/facebookresearch/poincare-embeddings#installation) you should have all dependencies [[1](https://github.com/facebookresearch/poincare-embeddings/blob/master/environment.yml#L6-L14)]

**Comment by jeskreiswinkler-etsy** [comment]
Thanks! I didn't realize I missed a step. Sorry to bug you :)
