### ISSUE TITLE
Error when running NIPS 2017 Release

### ISSUE THREAD

**Issue by hhchen1105** [facebookresearch/poincare-embeddings#64]
NIPS 2017 Release: https://github.com/facebookresearch/poincare-embeddings/releases/tag/1.0
When running  ``train-nouns.sh'',  I got the following error.  Could you please show me how to fix this?  Thanks.

Using 5 threads
slurp: objects=82115, edges=743086
Indexing data
json_conf: {"distfn": "poincare", "dim": 10, "lr": 1, "batchsize": 50, "negs": 50}
Burnin: lr=0.01
'Traceback (most recent call last):\n  File "/home/hhchen/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/hhchen/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/hhchen/proj/nips-2017-poincare/model.py", line 185, in __getitem__\n    if n not in self._weights[t]:\nKeyError: tensor(42545)\n'

**Comment by lematt1991** [comment]
Is there a reason you want to use such an old version of the repo?  The current state should be able to reproduce results from the paper.  The reason you are getting this error is because that tag uses a much older version of pytorch (0.3.0 I believe).

**Comment by hhchen1105** [comment]
Thanks for the information.  I use this old version mainly because the code structure is more straightforward for quick modification and experiments.  Based on your reply, I will go for the latest version.
