### ISSUE TITLE
[Question] Predicting the parent of an unseen word in an existing hierarchy

### ISSUE THREAD

**Issue by stelmath** [facebookresearch/poincare-embeddings#69]
Hello there,

I saw this [question](https://github.com/facebookresearch/poincare-embeddings/issues/67) and I am looking for something similar. 

But, in my case, let's say I have a list like:

parent | child
-- | --
animal | carnivore
carnivore | dog
dog | rottweiler
dog | huskey
dog | pug

From this list I can train a Poincare model and get poincare embeddings for every word/node in this hierarchy. Then, let's say I receive a new word: "dogo argentino". What I want at this point is a way to infer automatically that "dogo argentino" is the child of "dog". **Can poincare embeddings be of help here?** If ignoring poincare embeddings at all, a thought would be to get fastText embeddings for all the words, and find the word that is the closest (maybe in terms of cosine similarity) to the fastText embedding for "dogo argentino". Then assign the parent of that closest word, to the "dogo argentino" word. Any thoughts would be greatly appreciated. Thank you!

**Comment by lematt1991** [comment]
> If ignoring poincare embeddings at all, a thought would be to get fastText embeddings for all the words, and find the word that is the closest (maybe in terms of cosine similarity) to the fastText embedding for "dogo argentino". Then assign the parent of that closest word, to the "dogo argentino" word

You could try it.  FastText isn't going to respect the hierarchical structure of the embeddings space so there's certainly no guarantee that it will give you reasonable results, but it's possible that it will work out in practice.  I think the more principled approach is the one I mentioned in the [issue you listed](https://github.com/facebookresearch/poincare-embeddings/issues/67)

**Comment by stelmath** [comment]
@lematt1991 Thanks for the swift response! The difference from the linked issue is that in this issue we have:

> In this scenario, I know links/edges between the new node and existing embedded nodes.

In my case, **my goals is to find the link/edge between the new node and the existing nodes**. So, can trained poincare embeddings help or do they work only for nodes that are already in a taxonomy? Thanks!

**Comment by lematt1991** [comment]
Ah you're right that is an important distinction.  You could certainly try using FastText to do the link prediction part (find `k` nearest neighbors in FastText space for embeddings that exist in your taxonomy) and then trying to do some kind of hyperbolic aggregation of these neighbors as suggested in the other issue.

**Comment by stelmath** [comment]
Understood. Thanks again, cheers!
