### ISSUE TITLE
Why the Euclidean gradient omit the first part ?

### ISSUE THREAD

**Issue by buaaspy** [facebookresearch/poincare-embeddings#74]
https://github.com/facebookresearch/poincare-embeddings/blob/4c7316b14dce3b89e6a2d0c7994d418dffb42c94/hype/manifolds/poincare.py#L58

I am not sure if I was misunderstanding about the computation of Euclidean gradient. In the NIPS paper, the gradient is a product of gradient of L and partial derivatives of the poincare distance. However, by inspecting the code I only find the second part. So is there any point I missed ? I would be really grateful if any help is provided ! 

Thanks in advance !

**Comment by davecerr** [comment]
The grad function in line 58 corresponds to equation 4 in the paper. To see this, expand $\sqrt{\gamma^2-1}$ from equation 4 and also expand `z`from the function and show they are equivalent. Similarly, the term in brackets in equation 4 corresponds to `a `in the function.

**Comment by buaaspy** [comment]
> The grad function in line 58 corresponds to equation 4 in the paper (derivative of the Poincare distance). To see this, expand $\sqrt{\gamma^2-1}$ from equation 4 and also expand `z`from the function and show they are equivalent. Similarly, the term in brackets in equation 4 corresponds to `a `in the function.
> 
> It's correct that the full Euclidean gradient is a product of this term with the gradient of L w.r.t. the Poincare distance. However, the gradient of L is different depending on whether we are updating a vector w.r.t. a positive or negative relation.
> 
> I think if we look at the backwards function, you see the multiplication by the gradient of L being handled differently in each case.

Thank you very much !
