### ISSUE TITLE
How to get embeddings？

### ISSUE THREAD

**Issue by CallMeNumber1** [facebookresearch/poincare-embeddings#76]
I wonder what should i do to get poincare-embeddings after ruuning `./train-nouns.sh`, which will result in a '.pth' file, and then how to get embeddings from the '.pth' file?

**Comment by lematt1991** [comment]
This should do it:

```Python
import torch
chkpnt = torch.load('<path to checkpoint>')
embeddings = chkpnt['model']['lt.weight']
```
